FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm@9

COPY pnpm-workspace.yaml package.json .npmrc ./
COPY libs/common/package.json libs/common/
COPY backend/ms-gamify/package.json backend/ms-gamify/

RUN pnpm install

COPY tsconfig.base.json ./

WORKDIR /app/backend/ms-gamify

CMD ["pnpm", "dev"]
