export const TCP_PATTERNS = {
  AUTH: {
    PING: 'auth.ping',
    LOGIN: 'auth.login',
    REGISTER: 'auth.register',
    VALIDATE_TOKEN: 'auth.validate_token',
    GET_PROFILE: 'auth.get_profile',
    REFRESH: 'auth.refresh',
    LOGOUT: 'auth.logout',
    ADD_POINTS: 'auth.add_points',
    UPDATE_LEVEL: 'auth.update_level',
    LIST_USERS: 'auth.list_users',
  },
  REGISTER: {
    PING: 'register.ping',
    CREATE_REPORT: 'register.create_report',
    GET_REPORT: 'register.get_report',
    LIST_REPORTS: 'register.list_reports',
    GET_HEATMAP: 'register.get_heatmap',
    GET_HEATMAP_DETAILED: 'register.get_heatmap_detailed',
    VINCULAR_DEVICE: 'register.vincular_device',
    GET_IMAGEN: 'register.get_imagen',
  },
  ADMIN: {
    PING: 'admin.ping',
    LIST_PENDING: 'admin.list_pending',
    ACCEPT_REPORT: 'admin.accept_report',
    REJECT_REPORT: 'admin.reject_report',
    CREATE_GROUP: 'admin.create_group',
    UPDATE_CASE: 'admin.update_case',
    BAN_DEVICE: 'admin.ban_device',
    GET_GROUP: 'admin.get_group',
    LIST_GROUPS: 'admin.list_groups',
    LIST_GROUPS_BY_CELL: 'admin.list_groups_by_cell',
    GET_GROUPS_HEATMAP: 'admin.get_groups_heatmap',
    GET_CASE_TIMELINE: 'admin.get_case_timeline',
    DASHBOARD: 'admin.dashboard',
    DASHBOARD_KPIS: 'admin.dashboard_kpis',
    LIST_DEVICES: 'admin.list_devices',
    LIST_GROUP_REPORTS: 'admin.list_group_reports',
    LIST_NEARBY_REPORTS: 'admin.list_nearby_reports',
    UNBAN_DEVICE: 'admin.unban_device',
  },
  GAMIFY: {
    PING: 'gamify.ping',
    AWARD_POINTS: 'gamify.award_points',
    GET_USER_STATS: 'gamify.get_user_stats',
    GET_LEVELS: 'gamify.get_levels',
  },
} as const;
