export const TCP_PATTERNS = {
  AUTH: {
    PING: 'auth.ping',
    LOGIN: 'auth.login',
    REGISTER: 'auth.register',
    VALIDATE_TOKEN: 'auth.validate_token',
    GET_PROFILE: 'auth.get_profile',
    REFRESH: 'auth.refresh',
    LOGOUT: 'auth.logout',
  },
  REGISTER: {
    PING: 'register.ping',
    CREATE_REPORT: 'register.create_report',
    GET_REPORT: 'register.get_report',
    LIST_REPORTS: 'register.list_reports',
    GET_HEATMAP: 'register.get_heatmap',
    GET_HEATMAP_DETAILED: 'register.get_heatmap_detailed',
  },
  ADMIN: {
    PING: 'admin.ping',
    LIST_PENDING: 'admin.list_pending',
    ACCEPT_REPORT: 'admin.accept_report',
    REJECT_REPORT: 'admin.reject_report',
    CREATE_GROUP: 'admin.create_group',
    UPDATE_CASE: 'admin.update_case',
    BAN_DEVICE: 'admin.ban_device',
    GET_GROUP: 'admin.get_group',
    LIST_GROUPS: 'admin.list_groups',
    GET_CASE_TIMELINE: 'admin.get_case_timeline',
  },
  GAMIFY: {
    PING: 'gamify.ping',
    AWARD_POINTS: 'gamify.award_points',
    GET_USER_STATS: 'gamify.get_user_stats',
    GET_LEVELS: 'gamify.get_levels',
  },
} as const;
